name = "cf-workers-status-page"
workers_dev = true
compatibility_date = "2021-07-23"
main = "index.js"
type = "webpack"

[triggers]
crons = ["* * * * *"]

[site]
bucket = "out"

# uncomment and adjust following if you are not using GitHub Actions
[env.production]
kv-namespaces = [{binding="KV_STATUS_PAGE", id="988cb5cca4da49738bc896aa09b6e0ba", preview_id=""}]
#zone_id="xxx"
#route="xxx"
